tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
filter:
    excluded_paths:
        - 'tests/*'
build:
    dependencies:
        before:
            - '/usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-transport-thrift/2.3.0'
    environment:
        php: '5.4.28'
        elasticsearch: true
